services:
  - type: web
    runtime: node
    name: stremio-tv
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 7000
      - key: CACHE_ENABLED
        value: true
      - key: CACHE_TTL_MS
        value: 21600000
      - key: NODE_ENV
        value: production
      - key: SKIP_VOD
        value: true
